name: Test Docker image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          echo "JDK8"
          docker run -i $(docker build -q 8/jdk) /bin/sh -c "java -version && node --version"
          echo "JDK8 alpine"
          docker run -i $(docker build -q 8/jdk/alpine) /bin/sh -c "java -version && node --version"
          echo "JRE8"
          docker run -i $(docker build -q 8/jre) /bin/sh -c "java -version && node --version"
          echo "JRE8 alpine"
          docker run -i $(docker build -q 8/jre/alpine) /bin/sh -c "java -version && node --version"
          echo "JDK11"
          docker run -i $(docker build -q 11/jdk) /bin/sh -c "java -version && node --version"
          echo "JDK11 alpine"
          docker run -i $(docker build -q 11/jdk/alpine) /bin/sh -c "java -version && node --version"
          echo "JRE11"
          docker run -i $(docker build -q 11/jre) /bin/sh -c "java -version && node --version"
          echo "JRE11 alpine"
          docker run -i $(docker build -q 11/jre/alpine) /bin/sh -c "java -version && node --version"
