name: Test Docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker run -i $(docker build -q 8/jdk) /bin/sh -c "java -version && node --version"
          docker run -i $(docker build -q 8/jdk/slim) /bin/sh -c "java -version && node --version"
          docker run -i $(docker build -q 8/jdk/alpine) /bin/sh -c "java -version && node --version"
          docker run -i $(docker build -q 8/jre) /bin/sh -c "java -version && node --version"
          docker run -i $(docker build -q 8/jre/slim) /bin/sh -c "java -version && node --version"
          docker run -i $(docker build -q 8/jre/alpine) /bin/sh -c "java -version && node --version"
          docker run -i $(docker build -q 11/jdk) /bin/sh -c "java -version && node --version"
          docker run -i $(docker build -q 11/jdk/slim) /bin/sh -c "java -version && node --version"
          docker run -i $(docker build -q 11/jdk/alpine) /bin/sh -c "java -version && node --version"
          docker run -i $(docker build -q 11/jre) /bin/sh -c "java -version && node --version"
          docker run -i $(docker build -q 11/jre/slim) /bin/sh -c "java -version && node --version"
          docker run -i $(docker build -q 11/jre/alpine) /bin/sh -c "java -version && node --version"
